# Generated by Django 4.2.6 on 2023-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_details',
            field=models.TextField(blank=True),
        ),
    ]
