# Generated by Django 4.2.6 on 2023-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='isactive',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
