# Generated by Django 4.2.6 on 2023-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment_fees_alter_course_course_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='fees',
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
