# Generated by Django 4.2.6 on 2023-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_isactive_enrollment_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_course',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_course',
            field=models.DateTimeField(null=True),
        ),
    ]
