# Generated by Django 4.2.6 on 2023-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_end_course_course_start_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to='course-images/'),
        ),
    ]
