# Generated by Django 4.2.6 on 2023-10-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_html_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
