# Generated by Django 4.2.6 on 2023-10-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_course',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_course',
            field=models.DateField(null=True),
        ),
    ]
